"""replace age with birth_date

Revision ID: 41a264817180
Revises: f8d2a487f753
Create Date: 2025-11-11 11:41:56.785894

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '41a264817180'
down_revision = 'f8d2a487f753'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Travellers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=False))
        batch_op.alter_column('fitness',
               existing_type=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='fitness_level'),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', name='fitness_level_enum'),
               existing_nullable=True)
        batch_op.drop_column('age')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Travellers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.alter_column('fitness',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', name='fitness_level_enum'),
               type_=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='fitness_level'),
               existing_nullable=True)
        batch_op.drop_column('birth_date')

    # ### end Alembic commands ###
