"""Add destination column

Revision ID: 81bde77b4992
Revises: 41a264817180
Create Date: 2025-11-24 13:29:42.802782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81bde77b4992'
down_revision = '41a264817180'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Travellers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Name', sa.Text(), nullable=True))

    with op.batch_alter_table('Trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Destination', sa.Text(), nullable=True))
        batch_op.alter_column('preferences',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('ADVENTURE', 'CULTURE', 'RELAXATION', 'NATURE', name='pref_kind'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Trip', schema=None) as batch_op:
        batch_op.alter_column('preferences',
               existing_type=sa.Enum('ADVENTURE', 'CULTURE', 'RELAXATION', 'NATURE', name='pref_kind'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=True)
        batch_op.drop_column('Destination')

    with op.batch_alter_table('Travellers', schema=None) as batch_op:
        batch_op.drop_column('Name')

    # ### end Alembic commands ###
