"""Added latitude and longitude

Revision ID: 82de94d75418
Revises: bc5f5fadb812
Create Date: 2025-11-28 13:44:42.685262

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '82de94d75418'
down_revision = 'bc5f5fadb812'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Activity_type', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=30),
               existing_nullable=False)
        batch_op.alter_column('difficulty',
               existing_type=postgresql.ENUM('EASY', 'MODERATE', 'HARD', name='activity_difficulty_enum'),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('destination',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True)
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Activity_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
        batch_op.alter_column('destination',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('difficulty',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('EASY', 'MODERATE', 'HARD', name='activity_difficulty_enum'),
               existing_nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
