"""Initial migration

Revision ID: 9a65870944a4
Revises: 
Create Date: 2025-11-02 15:51:53.103160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9a65870944a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('Travellers')
    op.drop_table('Travel_agencies')
    op.drop_table('Hotel_Booking')
    op.drop_table('Activity_planned')
    op.drop_table('Trip')
    op.drop_table('Hotel')
    op.drop_table('Activity_type')
    op.drop_table('User')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('user_id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('Name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Phone_Number', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='User_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Activity_type',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('update_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('destination', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('difficulty', postgresql.ENUM('easy', 'moderate', 'hard', 'extreme', name='activity_difficulty'), autoincrement=False, nullable=True),
    sa.Column('Agency_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Agency_id'], ['Travel_agencies.id'], name='Activity_type_Agency_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Activities_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Hotel',
    sa.Column('Hotel_id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('adress', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Hotel_id', name='Hotel_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Trip',
    sa.Column('Trip_id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('Start_Date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('End_Date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('Number_Of_Travelers', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('preferences', postgresql.ENUM('budget', 'comfort', 'adventure', 'family', 'accessibility', 'other', name='pref_kind'), autoincrement=False, nullable=True),
    sa.Column('User_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['User_id'], ['User.user_id'], name='Trip_User_id_fkey'),
    sa.PrimaryKeyConstraint('Trip_id', name='Trip_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Activity_planned',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('Trip_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('Activity_type_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Activity_type_id'], ['Activity_type.id'], name=op.f('Activities_planned_Activity_type_id_fkey')),
    sa.ForeignKeyConstraint(['Trip_id'], ['Trip.Trip_id'], name=op.f('Activities_planned_Trip_id_fkey')),
    sa.PrimaryKeyConstraint('Trip_id', 'Activity_type_id', name=op.f('Activity_planned_pkey'))
    )
    op.create_table('Hotel_Booking',
    sa.Column('Booking_id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('Trip_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('check-in time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('check-out time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('Hotel_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Hotel_id'], ['Hotel.Hotel_id'], name=op.f('Hotel_Booking_Hotel_id_fkey')),
    sa.ForeignKeyConstraint(['Trip_id'], ['Trip.Trip_id'], name=op.f('Hotel_Booking_Trip_id_fkey')),
    sa.PrimaryKeyConstraint('Trip_id', 'Hotel_id', name=op.f('Hotel_Booking_pkey'))
    )
    op.create_table('Travel_agencies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('contact_info', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('website', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('Travel_agencies_pkey'))
    )
    op.create_table('Travellers',
    sa.Column('Traveller_id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('age', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('fitness', postgresql.ENUM('low', 'medium', 'high', name='fitness_level'), autoincrement=False, nullable=True),
    sa.Column('Trip_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Trip_id'], ['Trip.Trip_id'], name=op.f('Travelers_Trip_id_fkey')),
    sa.PrimaryKeyConstraint('Traveller_id', name=op.f('Travellers_pkey'))
    )
    op.drop_table('user')
    # ### end Alembic commands ###
