"""fresh start

Revision ID: bc5f5fadb812
Revises: 
Create Date: 2025-11-27 16:45:32.904496

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bc5f5fadb812'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Activity_type', schema=None) as batch_op:
       batch_op.alter_column(
              'difficulty',
              existing_type=sa.Enum('EASY', 'MODERATE', 'HARD', name='activity_difficulty'),
              type_=sa.Enum('EASY', 'MODERATE', 'HARD', name='activity_difficulty_enum'),
              existing_nullable=True,
              postgresql_using="difficulty::text::activity_difficulty_enum",
        )

    with op.batch_alter_table('Travel_agencies_id', schema=None) as batch_op:
        batch_op.alter_column('User_id',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('Travel_agencies_id_User_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'User', ['User_id'], ['user_id'])

    with op.batch_alter_table('Travellers', schema=None) as batch_op:
       batch_op.alter_column(
              'fitness',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', name='fitness_level'),
              type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', name='fitness_level_enum'),
              existing_nullable=True,
              postgresql_using="fitness::text::fitness_level_enum",
        )


    with op.batch_alter_table('Trip', schema=None) as batch_op:
        batch_op.alter_column('Number_Of_Travellers',
               existing_type=sa.BIGINT(),
               type_=sa.Numeric(),
               existing_nullable=True)
        batch_op.alter_column('Destination',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('Trip_User_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'User', ['User_id'], ['user_id'])

    with op.batch_alter_table('User', schema=None) as batch_op:
       batch_op.alter_column(
              'Role',
              existing_type=sa.Enum('AGENCY', 'TRAVELLER', name='Role'),
              type_=sa.Enum('TRAVELLER', 'AGENCY', name='user_role'),
              existing_nullable=True,
              postgresql_using='"Role"::text::user_role',
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.alter_column('Role',
               existing_type=sa.Enum('TRAVELLER', 'AGENCY', name='user_role'),
               type_=postgresql.ENUM('AGENCY', 'TRAVELLER', name='Role'),
               existing_nullable=False)

    with op.batch_alter_table('Trip', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('Trip_User_id_fkey'), 'User', ['User_id'], ['user_id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.alter_column('Destination',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('Number_Of_Travellers',
               existing_type=sa.Numeric(),
               type_=sa.BIGINT(),
               existing_nullable=True)

    with op.batch_alter_table('Travellers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.alter_column('fitness',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', name='fitness_level_enum'),
               type_=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='fitness_level'),
               existing_nullable=True)
        batch_op.alter_column('birth_date',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('Travel_agencies_id', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('Travel_agencies_id_User_id_fkey'), 'User', ['User_id'], ['user_id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.alter_column('User_id',
               existing_type=sa.BIGINT(),
               nullable=True)

    with op.batch_alter_table('Activity_type', schema=None) as batch_op:
        batch_op.alter_column('difficulty',
               existing_type=sa.Enum('EASY', 'MODERATE', 'HARD', name='activity_difficulty_enum'),
               type_=postgresql.ENUM('EASY', 'MODERATE', 'HARD', name='activity_difficulty'),
               existing_nullable=True)

    # ### end Alembic commands ###
