"""Fresh start

Revision ID: f8d2a487f753
Revises: 
Create Date: 2025-11-11 09:28:15.130680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8d2a487f753'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Travel_agencies',
    sa.Column('Agency_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('contact_info', sa.Text(), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('Agency_id')
    )
    op.create_table('User',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('Name', sa.Text(), nullable=True),
    sa.Column('Email', sa.Text(), nullable=True),
    sa.Column('Phone_Number', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('Email')
    )
    op.create_table('Activity_type',
    sa.Column('Activity_type_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('destination', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MODERATE', 'HARD', name='activity_difficulty'), nullable=True),
    sa.Column('Agency_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['Agency_id'], ['Travel_agencies.Agency_id'], ),
    sa.PrimaryKeyConstraint('Activity_type_id')
    )
    op.create_table('Trip',
    sa.Column('Trip_id', sa.BigInteger(), nullable=False),
    sa.Column('Start_Date', sa.Date(), nullable=True),
    sa.Column('End_Date', sa.Date(), nullable=True),
    sa.Column('Number_Of_Travellers', sa.Numeric(), nullable=True),
    sa.Column('preferences', sa.Enum('ADVENTURE', 'CULTURE', 'RELAX', name='pref_kind'), nullable=True),
    sa.Column('User_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['User_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('Trip_id')
    )
    op.create_table('Activity_planned',
    sa.Column('Trip_id', sa.BigInteger(), nullable=False),
    sa.Column('Activity_type_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['Activity_type_id'], ['Activity_type.Activity_type_id'], ),
    sa.ForeignKeyConstraint(['Trip_id'], ['Trip.Trip_id'], ),
    sa.PrimaryKeyConstraint('Trip_id', 'Activity_type_id')
    )
    op.create_table('Travellers',
    sa.Column('Traveller_id', sa.BigInteger(), nullable=False),
    sa.Column('age', sa.Date(), nullable=True),
    sa.Column('fitness', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='fitness_level'), nullable=True),
    sa.Column('Trip_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['Trip_id'], ['Trip.Trip_id'], ),
    sa.PrimaryKeyConstraint('Traveller_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Travellers')
    op.drop_table('Activity_planned')
    op.drop_table('Trip')
    op.drop_table('Activity_type')
    op.drop_table('User')
    op.drop_table('Travel_agencies')
    # ### end Alembic commands ###
